server:
  port: 8081
spring:
  application:
    name: "alpha-bcb"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/alpha-bcb"
  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
    virtual_host: "/"
    port: 5672
  datasource:
    url: "jdbc:mysql://localhost:3307/test?"
    username: "root"
    password: "example"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
