server:
  port: 8080
spring:
  application:
    name: "alpha-bcb"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/intermedio"
  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
    virtual_host: "/"
    port: 5672
  datasource:
    url: "jdbc:mysql://localhost/alpha-bcb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true"
    username: "root"
    password: "admin"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
